const root=document.documentElement;const themeToggle=document.querySelector('#themeToggle');const themeLabel=document.querySelector('#themeLabel');const authModal=document.querySelector('#authModal');const openLogin=document.querySelector('#openLogin');const closeModal=document.querySelector('#closeModal');const loginForm=document.querySelector('#loginForm');const registerForm=document.querySelector('#registerForm');const landingScreen=document.querySelector('#landingScreen');const workspace=document.querySelector('#workspace');const clearFiles=document.querySelector('#clearFiles');const fileList=document.querySelector('#fileList');
function forceNavVisibility(){if(!document.querySelector('#vectorNavEmergencyStyles')){const s=document.createElement('style');s.id='vectorNavEmergencyStyles';s.textContent='#workspace.vector-workspace.is-open{display:block!important;position:relative!important;z-index:10!important}#workspace.vector-workspace.is-open>.hover-nav{display:flex!important;visibility:visible!important;opacity:1!important;position:fixed!important;top:0!important;bottom:0!important;z-index:9000!important;pointer-events:auto!important;transform:none!important}#workspace.vector-workspace.is-open>.hover-nav--left{left:0!important;right:auto!important}#workspace.vector-workspace.is-open>.hover-nav--right{right:0!important;left:auto!important}.theme-toggle{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important}';document.head.appendChild(s)}document.querySelectorAll('#workspace > .hover-nav').forEach(n=>{n.style.display='flex';n.style.visibility='visible';n.style.opacity='1';n.style.position='fixed';n.style.top='0';n.style.bottom='0';n.style.zIndex='9000';n.style.pointerEvents='auto'});themeToggle?.setAttribute('hidden','true')}
function injectAsset(tag,attrs){const sel=tag==='link'?`link[href^="${attrs.href.split('?')[0]}"]`:`script[src^="${attrs.src.split('?')[0]}"]`;if(document.querySelector(sel))return;const el=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>{el[k]=v});document.head.appendChild(el)}
function loadLibraryAssets(){injectAsset('link',{rel:'stylesheet',href:'./supabase-library.css?v=20260704-1'});injectAsset('script',{src:'./supabase-library.js?v=20260704-1',defer:true});injectAsset('script',{src:'./map-item-filter.js?v=20260704-1',defer:true});injectAsset('script',{src:'./map-scale.js?v=20260704-1',defer:true});injectAsset('script',{src:'./map-layer-control.js?v=20260704-3',defer:true});injectAsset('script',{src:'./map-polygons-control.js?v=20260704-3',defer:true});injectAsset('link',{rel:'stylesheet',href:'./map-data.css?v=20260704-7'});injectAsset('script',{src:'./map-data.js?v=20260704-7',defer:true});injectAsset('link',{rel:'stylesheet',href:'./dict-editor.css?v=20260704-1'});injectAsset('script',{src:'./dict-editor.js?v=20260704-1',defer:true});injectAsset('script',{src:'./route-point-editor.js?v=20260704-2',defer:true});injectAsset('script',{src:'./map-network.js?v=20260704-1',defer:true})}
loadLibraryAssets();forceNavVisibility();
function ensureMapDataButton(){const r=document.querySelector('.hover-nav--right');if(!r||document.querySelector('#openMapDataButton'))return;const b=document.createElement('button');b.className='hover-nav__item';b.id='openMapDataButton';b.type='button';b.innerHTML='<img src="../assets/database-import.svg" alt=""><span>Дані</span>';b.addEventListener('click',()=>window.openMapDataDialog?.());r.insertBefore(b,r.firstChild);forceNavVisibility()}
function applyTheme(){root.dataset.theme='dark';localStorage.setItem('vector-theme','dark');if(themeLabel)themeLabel.textContent='Темна'}applyTheme();
function setAuthMode(m){document.querySelectorAll('.auth-tab[data-auth-mode]').forEach(t=>t.classList.toggle('is-active',t.dataset.authMode===m));loginForm?.classList.toggle('is-active',m==='login');registerForm?.classList.toggle('is-active',m==='register')}
function openAuth(m='login'){setAuthMode(m);authModal?.classList.add('is-open');authModal?.setAttribute('aria-hidden','false')}function closeAuth(){authModal?.classList.remove('is-open');authModal?.setAttribute('aria-hidden','true')}
openLogin?.addEventListener('click',()=>openAuth('login'));closeModal?.addEventListener('click',closeAuth);document.querySelectorAll('[data-auth-mode]').forEach(b=>b.addEventListener('click',()=>setAuthMode(b.dataset.authMode)));authModal?.addEventListener('click',e=>{if(e.target===authModal)closeAuth()});
function showSection(id){document.querySelectorAll('.nav__item').forEach(i=>i.classList.toggle('is-active',i.dataset.section===id));document.querySelectorAll('.section').forEach(s=>s.classList.toggle('is-active',s.id===id));ensureMapDataButton();forceNavVisibility()}document.querySelectorAll('.nav__item').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));
window.enterVector=function(){closeAuth();landingScreen?.setAttribute('hidden','true');document.querySelector('.landing-bg')?.setAttribute('hidden','true');workspace?.classList.add('is-open');workspace?.setAttribute('aria-hidden','false');localStorage.setItem('vector-user-session',JSON.stringify({email:'local'}));showSection('map');forceNavVisibility();setTimeout(()=>{ensureMapDataButton();forceNavVisibility();if(window.vectorMap?.invalidateSize)window.vectorMap.invalidateSize()},250)};
window.logoutVector=function(){workspace?.classList.remove('is-open');workspace?.setAttribute('aria-hidden','true');landingScreen?.removeAttribute('hidden');document.querySelector('.landing-bg')?.removeAttribute('hidden');localStorage.removeItem('vector-user-session')};
loginForm?.addEventListener('submit',e=>{e.preventDefault();window.enterVector()});registerForm?.addEventListener('submit',e=>{e.preventDefault();alert('Заявку зафіксовано локально.')});
function renderFileList(){if(!fileList)return;let files=[];try{files=JSON.parse(localStorage.getItem('vector-reference-files')||'[]')}catch{}if(!files.length){fileList.textContent='Файли ще не додані.';return}fileList.innerHTML=files.map(f=>`<div class="file-entry"><strong>${String(f.name||'')}</strong><span>${String(f.type||'')}</span><span>${f.importedTableId?'імпортована таблиця':''}</span></div>`).join('')}
clearFiles?.addEventListener('click',()=>{localStorage.removeItem('vector-reference-files');renderFileList()});renderFileList();ensureMapDataButton();forceNavVisibility();setInterval(forceNavVisibility,1200);try{const s=JSON.parse(localStorage.getItem('vector-user-session')||'null');if(s?.email)window.enterVector()}catch{}