(() => {
  let on=false, cv=null, points=[];
  let intensity=0.65, radiusBase=42, palette='magma';
  const PALETTES={
    magma:[['rgba(0,0,4,0)',0],['rgba(28,16,68,.18)',.25],['rgba(180,54,122,.34)',.55],['rgba(255,112,64,.46)',.78],['rgba(255,230,120,.62)',1]],
    mono:[['rgba(0,0,0,0)',0],['rgba(30,30,30,.18)',.35],['rgba(120,120,120,.34)',.65],['rgba(255,255,255,.55)',1]],
    uv:[['rgba(0,255,240,0)',0],['rgba(0,255,240,.16)',.28],['rgba(30,80,255,.30)',.52],['rgba(180,0,255,.42)',.76],['rgba(255,255,255,.56)',1]]
  };
  function M(){try{return window.vectorLeafletMap||window.vectorMap||eval('vectorMap')}catch{return null}}
  function css(){
    if(document.querySelector('#hmcss'))return;
    let s=document.createElement('style');s.id='hmcss';s.textContent=`
      .hm{position:fixed;right:92px;top:620px;width:54px;height:54px;z-index:100002;background:#090f1a;color:white;border:1px solid #555;border-radius:14px;font-weight:900;box-shadow:0 16px 38px rgba(0,0,0,.42)}.hm.on{border-color:#d78219;color:#d78219}
      .hmPanel{position:fixed;right:154px;top:590px;width:340px;z-index:100003;display:none;padding:16px;border:1px solid rgba(215,130,25,.42);background:rgba(10,23,48,.95);box-shadow:0 24px 70px rgba(0,0,0,.45);font-family:Rajdhani,Arial,sans-serif;border-radius:16px;color:#fff}.hmPanel.open{display:block}
      .hmHead{display:flex;justify-content:space-between;gap:12px;margin-bottom:12px}.hmHead b{font-size:22px;text-transform:uppercase;letter-spacing:.14em}.hmHead button{background:none;border:0;color:#fff;font-size:24px;cursor:pointer}.hmHelp{color:#b7c3d4;font-size:14px;margin:-4px 0 14px}.hmBlock{margin:13px 0}.hmLbl{display:flex;justify-content:space-between;color:#ffb055;font-weight:800;text-transform:uppercase;letter-spacing:.1em;margin-bottom:7px}.hmRange{width:100%;accent-color:#d78219}.hmStyles{display:grid;gap:8px}.hmStyle{display:grid;grid-template-columns:1fr 120px;gap:10px;align-items:center;padding:10px 12px;border:1px solid rgba(255,255,255,.12);border-radius:10px;background:rgba(17,35,68,.68);cursor:pointer}.hmStyle.active{border-color:#d78219}.hmGrad{height:18px;border-radius:5px}.hmGrad.magma{background:linear-gradient(90deg,#05000a,#48146b,#b4367a,#ff7040,#ffe678)}.hmGrad.mono{background:linear-gradient(90deg,#000,#555,#aaa,#fff)}.hmGrad.uv{background:linear-gradient(90deg,#00fff0,#1e50ff,#b400ff,#fff)}.hmActions{display:flex;gap:8px;margin-top:13px}.hmActions button{flex:1;padding:10px;border:1px solid rgba(215,130,25,.45);background:rgba(255,255,255,.05);color:#fff;text-transform:uppercase;font-weight:800;letter-spacing:.12em;cursor:pointer}.hmActions .main{background:rgba(215,130,25,.18);color:#ffb055}`;
    document.head.appendChild(s)
  }
  function btn(){css();if(document.querySelector('#hm'))return;let b=document.createElement('button');b.id='hm';b.className='hm';b.textContent='HM';b.onclick=()=>togglePanel();document.body.appendChild(b);panel()}
  function panel(){
    if(document.querySelector('#hmPanel'))return;
    let p=document.createElement('section');p.id='hmPanel';p.className='hmPanel';p.innerHTML=`<div class="hmHead"><b>Теплокарта</b><button id="hmClose">×</button></div><div class="hmHelp">Будується з активних точкових шарів. Інші елементи залишаються поверх.</div><div class="hmBlock"><div class="hmLbl"><span>Інтенсивність</span><span id="hmIntVal">65%</span></div><input class="hmRange" id="hmIntensity" type="range" min="10" max="100" value="65"></div><div class="hmBlock"><div class="hmLbl"><span>Розмір плями</span><span id="hmRadVal">42</span></div><input class="hmRange" id="hmRadius" type="range" min="18" max="90" value="42"></div><div class="hmBlock"><div class="hmLbl"><span>Стиль</span></div><div class="hmStyles"><div class="hmStyle active" data-pal="magma"><strong>Магма</strong><i class="hmGrad magma"></i></div><div class="hmStyle" data-pal="mono"><strong>Чорно-біла</strong><i class="hmGrad mono"></i></div><div class="hmStyle" data-pal="uv"><strong>Ультрафіолет</strong><i class="hmGrad uv"></i></div></div></div><div class="hmActions"><button id="hmClear">Очистити</button><button class="main" id="hmApply">Застосувати</button></div>`;document.body.appendChild(p);
    p.querySelector('#hmClose').onclick=()=>togglePanel(false);p.querySelector('#hmClear').onclick=clear;p.querySelector('#hmApply').onclick=draw;
    p.querySelector('#hmIntensity').oninput=e=>{intensity=Number(e.target.value)/100;p.querySelector('#hmIntVal').textContent=e.target.value+'%';redraw()};
    p.querySelector('#hmRadius').oninput=e=>{radiusBase=Number(e.target.value);p.querySelector('#hmRadVal').textContent=e.target.value;redraw()};
    p.querySelectorAll('.hmStyle').forEach(x=>x.onclick=()=>{palette=x.dataset.pal;p.querySelectorAll('.hmStyle').forEach(y=>y.classList.toggle('active',y===x));redraw()})
  }
  function togglePanel(force){panel();let p=document.querySelector('#hmPanel');let show=force===undefined?!p.classList.contains('open'):force;p.classList.toggle('open',show);document.querySelector('#hm')?.classList.toggle('on',show||on)}
  function pts(){let r=window.vectorLayerRegistry||{},a=[];['uav','stations','vp','sp','points','settlements'].forEach(k=>(r[k]||[]).forEach(l=>{let p=l.getLatLng?l.getLatLng():null;if(!p&&l.getBounds)p=l.getBounds().getCenter();if(p)a.push([p.lat,p.lng])}));return a}
  function draw(){let m=M();if(!m)return;clear(false);points=pts();cv=document.createElement('canvas');cv.style.position='absolute';cv.style.pointerEvents='none';cv.style.zIndex='420';m.getPane('overlayPane').appendChild(cv);on=true;document.querySelector('#hm')?.classList.add('on');redraw();if(!m.hm){m.on('move zoom resize',()=>redraw());m.hm=1}}
  function redraw(){let m=M();if(!m||!cv)return;let z=m.getSize();cv.width=z.x;cv.height=z.y;let tl=m.containerPointToLayerPoint([0,0]);cv.style.width=z.x+'px';cv.style.height=z.y+'px';cv.style.transform='translate('+tl.x+'px,'+tl.y+'px)';let c=cv.getContext('2d');c.clearRect(0,0,cv.width,cv.height);points.forEach(x=>{let q=m.latLngToContainerPoint(x),r=Math.max(12,radiusBase-m.getZoom()*1.2);let g=c.createRadialGradient(q.x,q.y,0,q.x,q.y,r);PALETTES[palette].forEach(([col,pos])=>g.addColorStop(pos,col.replace(/\.\d+\)/,m0=>m0).replace(/rgba\(([^,]+),([^,]+),([^,]+),([^\)]+)\)/,(mm,a,b,d,alpha)=>`rgba(${a},${b},${d},${Number(alpha)*intensity})`)));c.fillStyle=g;c.beginPath();c.arc(q.x,q.y,r,0,6.3);c.fill()})}
  function clear(update=true){cv&&cv.remove();cv=null;on=false;points=[];if(update)document.querySelector('#hm')?.classList.toggle('on',document.querySelector('#hmPanel')?.classList.contains('open'))}
  window.vectorHeatmap={button:btn,build:draw,clear,redraw};window.addEventListener('load',()=>{btn();setInterval(btn,1000)});btn();
})();