(() => {
let on=false,cv=null,pts=[];let inten=.65,rad=42,pal='magma';
const colors={magma:[[5,0,10,0],[72,20,107,.22],[180,54,122,.42],[255,112,64,.64],[255,230,120,.82]],mono:[[0,0,0,0],[45,45,45,.22],[140,140,140,.42],[255,255,255,.72]],uv:[[0,255,240,0],[0,255,240,.22],[30,80,255,.40],[180,0,255,.62],[255,255,255,.80]]};
function M(){return window.vectorLeafletMap||window.vectorMap||null}
function css(){if(document.querySelector('#hmcss'))return;let s=document.createElement('style');s.id='hmcss';s.textContent='.hm{position:fixed;right:92px;top:620px;width:54px;height:54px;z-index:100002;background:#090f1a;color:white;border:1px solid #555;border-radius:14px;font-weight:900;box-shadow:0 16px 38px rgba(0,0,0,.42)}.hm.on{border-color:#d78219;color:#d78219}.hmPanel{position:fixed;right:154px;top:590px;width:340px;z-index:100003;display:none;padding:16px;border:1px solid rgba(215,130,25,.42);background:rgba(10,23,48,.95);box-shadow:0 24px 70px rgba(0,0,0,.45);font-family:Rajdhani,Arial,sans-serif;border-radius:16px;color:#fff}.hmPanel.open{display:block}.hmHead{display:flex;justify-content:space-between;margin-bottom:12px}.hmHead b{font-size:22px;text-transform:uppercase;letter-spacing:.14em}.hmHead button{background:none;border:0;color:#fff;font-size:24px}.hmHelp{color:#b7c3d4;font-size:14px;margin:-4px 0 14px}.hmBlock{margin:13px 0}.hmLbl{display:flex;justify-content:space-between;color:#ffb055;font-weight:800;text-transform:uppercase;letter-spacing:.1em;margin-bottom:7px}.hmRange{width:100%;accent-color:#d78219}.hmStyles{display:grid;gap:8px}.hmStyle{display:grid;grid-template-columns:1fr 120px;gap:10px;padding:10px 12px;border:1px solid rgba(255,255,255,.12);border-radius:10px;background:rgba(17,35,68,.68);cursor:pointer}.hmStyle.active{border-color:#d78219}.hmGrad{height:18px;border-radius:5px}.hmGrad.magma{background:linear-gradient(90deg,#05000a,#48146b,#b4367a,#ff7040,#ffe678)}.hmGrad.mono{background:linear-gradient(90deg,#000,#555,#aaa,#fff)}.hmGrad.uv{background:linear-gradient(90deg,#00fff0,#1e50ff,#b400ff,#fff)}.hmActions{display:flex;gap:8px;margin-top:13px}.hmActions button{flex:1;padding:10px;border:1px solid rgba(215,130,25,.45);background:rgba(255,255,255,.05);color:#fff;text-transform:uppercase;font-weight:800;letter-spacing:.12em}.hmActions .main{background:rgba(215,130,25,.18);color:#ffb055}';document.head.appendChild(s)}
function btn(){css();if(document.querySelector('#hm'))return;let b=document.createElement('button');b.id='hm';b.className='hm';b.textContent='HM';b.onclick=()=>toggle();document.body.appendChild(b);panel()}
function panel(){if(document.querySelector('#hmPanel'))return;let p=document.createElement('section');p.id='hmPanel';p.className='hmPanel';p.innerHTML='<div class="hmHead"><b>Теплокарта</b><button id="hmClose">×</button></div><div class="hmHelp">Точки зливаються в одну безшовну теплову поверхню.</div><div class="hmBlock"><div class="hmLbl"><span>Інтенсивність</span><span id="hmIntVal">65%</span></div><input class="hmRange" id="hmIntensity" type="range" min="10" max="100" value="65"></div><div class="hmBlock"><div class="hmLbl"><span>Розмір плями</span><span id="hmRadVal">42</span></div><input class="hmRange" id="hmRadius" type="range" min="18" max="90" value="42"></div><div class="hmBlock"><div class="hmLbl"><span>Стиль</span></div><div class="hmStyles"><div class="hmStyle active" data-pal="magma"><strong>Магма</strong><i class="hmGrad magma"></i></div><div class="hmStyle" data-pal="mono"><strong>Чорно-біла</strong><i class="hmGrad mono"></i></div><div class="hmStyle" data-pal="uv"><strong>Ультрафіолет</strong><i class="hmGrad uv"></i></div></div></div><div class="hmActions"><button id="hmClear">Очистити</button><button class="main" id="hmApply">Застосувати</button></div>';document.body.appendChild(p);p.querySelector('#hmClose').onclick=()=>toggle(false);p.querySelector('#hmClear').onclick=clear;p.querySelector('#hmApply').onclick=draw;p.querySelector('#hmIntensity').oninput=e=>{inten=Number(e.target.value)/100;p.querySelector('#hmIntVal').textContent=e.target.value+'%';redraw()};p.querySelector('#hmRadius').oninput=e=>{rad=Number(e.target.value);p.querySelector('#hmRadVal').textContent=e.target.value;redraw()};p.querySelectorAll('.hmStyle').forEach(x=>x.onclick=()=>{pal=x.dataset.pal;p.querySelectorAll('.hmStyle').forEach(y=>y.classList.toggle('active',y===x));redraw()})}
function toggle(force){panel();let p=document.querySelector('#hmPanel'),show=force===undefined?!p.classList.contains('open'):force;p.classList.toggle('open',show);document.querySelector('#hm')?.classList.toggle('on',show||on)}
function collect(){let r=window.vectorLayerRegistry||{},a=[];['uav','stations','vp','sp','points','settlements'].forEach(k=>(r[k]||[]).forEach(l=>{let p=l.getLatLng?l.getLatLng():null;if(!p&&l.getBounds)p=l.getBounds().getCenter();if(p)a.push([p.lat,p.lng])}));return a}
function draw(){let m=M();if(!m)return;clear(false);pts=collect();cv=document.createElement('canvas');cv.style.position='absolute';cv.style.pointerEvents='none';cv.style.zIndex='420';m.getPane('overlayPane').appendChild(cv);on=true;document.querySelector('#hm')?.classList.add('on');redraw();if(!m.hm){m.on('move zoom resize',()=>redraw());m.hm=1}}
function cval(t){let p=colors[pal],x=t*(p.length-1),i=Math.min(p.length-2,Math.floor(x)),f=x-i,a=p[i],b=p[i+1];return[a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f,a[2]+(b[2]-a[2])*f,(a[3]+(b[3]-a[3])*f)*inten]}
function redraw(){let m=M();if(!m||!cv)return;let z=m.getSize();cv.width=z.x;cv.height=z.y;let tl=m.containerPointToLayerPoint([0,0]);cv.style.width=z.x+'px';cv.style.height=z.y+'px';cv.style.transform='translate('+tl.x+'px,'+tl.y+'px)';let ctx=cv.getContext('2d');ctx.clearRect(0,0,cv.width,cv.height);let mask=document.createElement('canvas');mask.width=cv.width;mask.height=cv.height;let mx=mask.getContext('2d'),rr=Math.max(14,rad-m.getZoom()*1.2);pts.forEach(x=>{let q=m.latLngToContainerPoint(x),g=mx.createRadialGradient(q.x,q.y,0,q.x,q.y,rr);g.addColorStop(0,'rgba(255,255,255,.52)');g.addColorStop(.62,'rgba(255,255,255,.23)');g.addColorStop(1,'rgba(255,255,255,0)');mx.fillStyle=g;mx.beginPath();mx.arc(q.x,q.y,rr,0,6.3);mx.fill()});let img=mx.getImageData(0,0,mask.width,mask.height),d=img.data,out=ctx.createImageData(mask.width,mask.height),o=out.data;for(let i=0;i<d.length;i+=4){let a=d[i+3]/255;if(a<.035){o[i+3]=0;continue}let cc=cval(Math.min(1,a*1.65));o[i]=cc[0];o[i+1]=cc[1];o[i+2]=cc[2];o[i+3]=Math.round(cc[3]*255)}ctx.putImageData(out,0,0)}
function clear(update=true){cv&&cv.remove();cv=null;on=false;pts=[];if(update)document.querySelector('#hm')?.classList.toggle('on',document.querySelector('#hmPanel')?.classList.contains('open'))}
window.vectorHeatmap={button:btn,build:draw,clear,redraw};window.addEventListener('load',()=>{btn();setInterval(btn,1000)});btn();
})();