(() => {
  const KEYS=['summary','uav','stations','stationRadius','vp','sp','routes','points','polygons','settlements'];
  const NAMES={summary:'Зведені НП',uav:'БПЛА',stations:'Станції',stationRadius:'Радіуси станцій',vp:'ВП',sp:'СП',routes:'Маршрути',points:'Пункти',polygons:'Полігони',settlements:'Населені пункти'};
  const COLORS={uav:'#3B82F6',stations:'#22C55E',stationRadius:'#22C55E',vp:'#EF4444',sp:'#FACC15',routes:'#F97316',points:'#EC4899',polygons:'#16A34A',summary:'#8B5CF6',settlements:'#94A3B8'};
  function map(){return window.vectorLeafletMap||window.vectorMap||null}
  function registry(){return window.vectorLayerRegistry||{}}
  function css(){if(document.querySelector('#exportCss'))return;const s=document.createElement('style');s.id='exportCss';s.textContent=`
    .exportBtn{position:fixed;right:92px;top:684px;width:54px;height:54px;z-index:100002;border:1px solid rgba(255,255,255,.18);background:rgba(9,15,26,.96);color:#fff;border-radius:14px;cursor:pointer;font:900 17px Rajdhani,Arial;display:flex;align-items:center;justify-content:center;box-shadow:0 16px 38px rgba(0,0,0,.42)}.exportBtn:hover,.exportBtn.is-active{border-color:#d78219;color:#d78219}
    .exportModal{position:fixed;inset:0;z-index:200000;display:none;align-items:center;justify-content:center;background:rgba(4,9,18,.58);backdrop-filter:blur(5px);font-family:Rajdhani,Arial,sans-serif}.exportModal.open{display:flex}
    .exportPanel{width:min(1500px,92vw);height:min(820px,88vh);display:grid;grid-template-columns:390px 1fr;gap:22px;padding:22px;border:1px solid rgba(90,130,210,.35);border-radius:24px;background:linear-gradient(145deg,rgba(14,29,61,.98),rgba(8,18,38,.98));box-shadow:0 30px 90px rgba(0,0,0,.55);color:#fff}.exportSide h2{margin:0 0 12px;font-size:28px}.exportSide label{display:block;margin:12px 0 6px;font-weight:800;color:#dbe7ff}.exportSide input[type=text]{width:100%;box-sizing:border-box;padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:14px;background:#08142d;color:#fff;font:700 16px Rajdhani,Arial}.exportChecks{margin:14px 0;padding:12px;border:1px solid rgba(255,255,255,.1);border-radius:16px;background:rgba(255,255,255,.04)}.exportChecks label{display:flex;gap:10px;align-items:center;margin:10px 0;color:#e8f0ff}.exportChecks input{accent-color:#3B82F6}.exportButtons{display:grid;gap:10px;margin-top:14px}.exportButtons button{padding:13px;border:0;border-radius:12px;color:#fff;font:900 16px Rajdhani,Arial;cursor:pointer}.expPng{background:#3B82F6}.expXls{background:#24B47E}.expPdf{background:#526987}.expClose{background:#465B82}.exportPreview{position:relative;border-radius:18px;overflow:hidden;background:#f8fafc;border:1px solid rgba(255,255,255,.16)}.exportMapClone{position:absolute;inset:0;background:#f8fafc}.exportOverlay{position:absolute;inset:0;pointer-events:none}.expTitle{position:absolute;left:22px;top:20px;padding:10px 16px;background:rgba(8,18,32,.78);border-radius:12px;color:white;font:900 30px Rajdhani,Arial}.expLegend{position:absolute;left:22px;top:96px;padding:14px 16px;background:rgba(8,18,32,.75);border-radius:14px;color:white;min-width:200px}.expLegend b{display:block;margin-bottom:8px}.expLegend div{display:flex;align-items:center;gap:8px;margin:6px 0}.expDot{width:12px;height:12px;border-radius:50%;display:inline-block}.expNorth{position:absolute;right:20px;top:20px;width:48px;height:66px;background:rgba(8,18,32,.76);border-radius:14px;display:flex;align-items:center;justify-content:center;color:#fff;font:900 15px Rajdhani,Arial}.expNorth:before{content:'▲';position:absolute;top:8px;font-size:20px}.expNorth span{margin-top:22px}.expScale{position:absolute;left:50%;bottom:18px;transform:translateX(-50%);padding:10px 20px;background:rgba(8,18,32,.78);border-radius:14px;color:#fff;font:900 22px Rajdhani,Arial}.expKpi{position:absolute;left:22px;bottom:20px;padding:12px 16px;background:rgba(8,18,32,.74);border-radius:14px;color:#fff;min-width:180px}.expInfo{position:absolute;right:22px;bottom:20px;padding:12px 16px;background:rgba(8,18,32,.74);border-radius:14px;color:#fff}.expStatus{margin-top:10px;color:#b7c3d4;font-size:14px}`;document.head.appendChild(s)}
  function btn(){css();if(document.querySelector('#exportBtn'))return;const b=document.createElement('button');b.id='exportBtn';b.className='exportBtn';b.type='button';b.title='Експорт карти';b.textContent='EX';b.onclick=()=>open();document.body.appendChild(b)}
  function modal(){css();let m=document.querySelector('#exportModal');if(m)return m;m=document.createElement('section');m.id='exportModal';m.className='exportModal';m.innerHTML=`<div class="exportPanel"><div class="exportSide"><h2>Експорт карти</h2><label>Назва карти</label><input id="expName" type="text" placeholder="Введіть назву карти"><label>Виконавець</label><input id="expAuthor" type="text" placeholder="Ім'я та прізвище"><div class="exportChecks"><label><input id="expTitleOn" type="checkbox" checked> Назва карти</label><label><input id="expLegendOn" type="checkbox" checked> Легенда</label><label><input id="expScaleOn" type="checkbox" checked> Масштаб</label><label><input id="expNorthOn" type="checkbox" checked> Північ</label><label><input id="expInfoOn" type="checkbox" checked> Службова інформація</label><label><input id="expKpiOn" type="checkbox" checked> KPI</label><label><input id="expGridOn" type="checkbox"> Координаційна сітка</label></div><div class="exportButtons"><button class="expPng" id="expPng">PNG</button><button class="expXls" id="expXls">Excel</button><button class="expPdf" id="expPdf">PDF</button><button class="expClose" id="expClose">Закрити</button></div><div class="expStatus" id="expStatus">Готово.</div></div><div class="exportPreview" id="exportPreview"><div id="exportMapClone" class="exportMapClone"></div><div class="exportOverlay"><div class="expTitle" id="expTitleBox">Без назви</div><div class="expLegend" id="expLegendBox"><b>Легенда</b></div><div class="expNorth" id="expNorthBox"><span>N</span></div><div class="expScale" id="expScaleBox">1:—</div><div class="expKpi" id="expKpiBox"></div><div class="expInfo" id="expInfoBox"></div></div></div></div>`;document.body.appendChild(m);m.querySelector('#expClose').onclick=close;m.querySelector('#expPng').onclick=exportPng;m.querySelector('#expXls').onclick=exportXlsx;m.querySelector('#expPdf').onclick=()=>setStatus('PDF додамо наступним етапом.');m.querySelectorAll('input').forEach(i=>i.addEventListener('input',renderPreview));return m}
  function open(){modal().classList.add('open');document.querySelector('#exportBtn')?.classList.add('is-active');renderPreview();}
  function close(){document.querySelector('#exportModal')?.classList.remove('open');document.querySelector('#exportBtn')?.classList.remove('is-active')}
  function setStatus(t){const e=document.querySelector('#expStatus');if(e)e.textContent=t}
  function currentScale(){const e=document.querySelector('#vectorScaleBox,#scaleBox,.scale-box');return e?.textContent?.replace('МАСШТАБ','').trim()||'1:—'}
  function counts(){const r=registry(),o={};KEYS.forEach(k=>o[k]=r[k]?.size||0);return o}
  function layerPoints(){const rows=[];const r=registry();KEYS.forEach(k=>(r[k]||[]).forEach((l,i)=>{let p=l.getLatLng?l.getLatLng():null;if(!p&&l.getBounds)p=l.getBounds().getCenter();rows.push({layer:NAMES[k]||k,index:i+1,lat:p?.lat||'',lon:p?.lng||'',radius_m:l.getRadius?.()||'',type:k})}));return rows}
  function calcArea(){const r=registry();let stationArea=0;(r.stationRadius||[]).forEach(l=>{const rm=Number(l.getRadius?.()||0);if(rm)stationArea+=Math.PI*(rm/1000)**2});let boundsArea='';try{const m=map(),b=m.getBounds(),R=6371,w=Math.abs(b.getEast()-b.getWest())*Math.PI/180*Math.cos(((b.getNorth()+b.getSouth())/2)*Math.PI/180)*R,h=Math.abs(b.getNorth()-b.getSouth())*Math.PI/180*R;boundsArea=w*h}catch{}return{station_area_km2:stationArea,bounds_area_km2:boundsArea,coverage_percent:boundsArea?Math.min(100,stationArea/boundsArea*100):''}}
  function kpiText(){const c=counts(),a=calcArea();return `Об'єктів: ${Object.values(c).reduce((s,x)=>s+x,0)}<br>Станцій: ${c.stations}<br>Покриття: ${a.coverage_percent===''?'—':a.coverage_percent.toFixed(1)+'%'}`}
  function legendHtml(){const c=counts();return Object.keys(c).filter(k=>c[k]).map(k=>`<div><i class="expDot" style="background:${COLORS[k]||'#fff'}"></i><span>${NAMES[k]||k}: ${c[k]}</span></div>`).join('')||'<div>Немає активних шарів</div>'}
  async function cloneMap(){const target=document.querySelector('#exportMapClone');const src=document.querySelector('#vectorMap');if(!target||!src)return;target.innerHTML='';const node=src.cloneNode(true);node.removeAttribute('id');node.style.width='100%';node.style.height='100%';node.style.position='absolute';node.style.inset='0';target.appendChild(node)}
  function renderPreview(){cloneMap();const name=document.querySelector('#expName')?.value||'Без назви',author=document.querySelector('#expAuthor')?.value||'Не вказано';const c=id=>document.querySelector(id)?.checked;document.querySelector('#expTitleBox').textContent=name;document.querySelector('#expTitleBox').style.display=c('#expTitleOn')?'':'none';document.querySelector('#expLegendBox').style.display=c('#expLegendOn')?'':'none';document.querySelector('#expLegendBox').innerHTML='<b>Легенда</b>'+legendHtml();document.querySelector('#expNorthBox').style.display=c('#expNorthOn')?'':'none';document.querySelector('#expScaleBox').style.display=c('#expScaleOn')?'':'none';document.querySelector('#expScaleBox').textContent=currentScale();document.querySelector('#expKpiBox').style.display=c('#expKpiOn')?'':'none';document.querySelector('#expKpiBox').innerHTML='<b>KPI</b><br>'+kpiText();document.querySelector('#expInfoBox').style.display=c('#expInfoOn')?'':'none';document.querySelector('#expInfoBox').innerHTML='Виконавець: '+author+'<br>Згенеровано: '+new Date().toLocaleString('uk-UA')}
  function loadHtml2Canvas(){return window.html2canvas?Promise.resolve():new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
  async function exportPng(){try{setStatus('Генерую PNG...');renderPreview();await loadHtml2Canvas();const canvas=await html2canvas(document.querySelector('#exportPreview'),{useCORS:true,backgroundColor:'#f8fafc',scale:2});const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download=(document.querySelector('#expName')?.value||'vector-map')+'.png';a.click();setStatus('PNG готовий.')}catch(e){console.warn(e);setStatus('Не вдалося створити PNG через обмеження CORS тайлів.')}}
  function exportXlsx(){try{if(!window.XLSX){setStatus('XLSX бібліотека не завантажена.');return}const wb=XLSX.utils.book_new();const c=counts(),a=calcArea();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{map_name:document.querySelector('#expName')?.value||'Без назви',author:document.querySelector('#expAuthor')?.value||'',generated_at:new Date().toLocaleString('uk-UA'),total_objects:Object.values(c).reduce((s,x)=>s+x,0),stations:c.stations,uav:c.uav,vp:c.vp,sp:c.sp,points:c.points,routes:c.routes,station_area_km2:a.station_area_km2,bounds_area_km2:a.bounds_area_km2,coverage_percent:a.coverage_percent}]),'Розрахунки');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(Object.keys(c).map(k=>({layer:NAMES[k]||k,count:c[k]}))),'Кількість');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(layerPoints()),'Перелік');XLSX.writeFile(wb,(document.querySelector('#expName')?.value||'vector-export')+'.xlsx');setStatus('Excel готовий.')}catch(e){console.warn(e);setStatus('Не вдалося створити Excel.')}}
  window.vectorExport={button:btn,open,close,exportXlsx,exportPng};function boot(){btn();modal()}boot();window.addEventListener('load',()=>{boot();setInterval(btn,1000)});
})();